### PR TITLE
get_toolchain.sh: Update broken link

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jockebech** [comment]
`Acked-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by vchong** [comment]
Tag added. Thanks!

**Comment by vchong** [comment]
Ok to merge this too?

**Comment by jforissier** [comment]
Who's the maintainer for this project?

**Comment by vchong** [comment]
I don't know either. @d3zd3z? I figured anyone of you can probably merge this since it's only a link fix?

**Comment by jockebech** [comment]
Yes, it's David (@d3zd3z), but it's still git in our working group (and not a private git), so I see no problems in someone else merging here as long as there is a review tag. I'm pretty sure David agrees, especially now when he's currently not doing any work with this. But thanks for asking.

**Pull request merged**
